[package]
name = "map-to-vid"
version = "0.1.0"
authors = ["David Koerver"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
#mpeg_encoder = "0.2.1"
